version: '3'

services:

  consul-agent-1: &consul-agent
    image: consul:1.6.0
    networks:
      - consul-demo
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -ui -client 0.0.0.0"
    ports:
      - "5400:8400"
      - "5500:8500"
      - "5600:8600"
      - "5600:8600/udp"

  consul-server-2:
    <<: *consul-server
    ports:
      - "6400:8400"
      - "6500:8500"
      - "6600:8600"
      - "6600:8600/udp"

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "7400:8400"
      - "7500:8500"
      - "7600:8600"
      - "7600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

  consul-server-lb:
    #net-tools, dnsutils, curl, procps
    image: nginx
    networks:
      - consul-demo
    volumes:
     - ./consul_server_lb/rawconf.d/:/etc/nginx/rawconf.d/
     - ./consul_server_lb/httpconf.d/:/etc/nginx/httpconf.d/
     - ./consul_server_lb/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"

networks:
  consul-demo:
